### PR TITLE
Pass url to Faraday connection to support no_proxy

### LINKED ISSUE #182: Does not work with no_proxy
Per https://github.com/lostisland/faraday/issues/701#issuecomment-307401441

 > when you call Faraday.get without first initialising the connection, a Faraday::Connection with no url is created to perform the request. This causes the find_default_proxy method to be triggered, without no_proxy support 

[This code](https://github.com/rsolr/rsolr/blob/c8139594753b355ade6d621dc1fbb34779643e8f/lib/rsolr/client.rb#L278-L291) is creating a connection with no url, so `no_proxy` is not supported.

```
[1] pry(main)> ENV['no_proxy']
=> "localhost,127.0.0.1,172.22.24.151,cdlxutl301.candrugcorp.net"
[2] pry(main)> RSolr.connect(url: 'http://localhost:8983').get 'select', :params => {:q => '*:*'}
no_proxy is unsupported
D, [2017-06-09T09:27:31.732344 #20465] DEBUG -- :   SOLR Request (17.5ms)  [ path=select parameters={q: "*:*"} ]
RSolr::Error::Http: RSolr::Error::Http - 503 Service Unavailable
Error: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" CONTENT="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!-- 
 /*
 Stylesheet for Squid Error pages
 Adapted from design by Free CSS Templates
 http://www.freecsstemplates.org
 Released for free under a Creative Commons Attribution 2.5 License
*/

URI: http://localhost:8983/select?wt=json&q=*%3A*

Backtrace: /home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/rsolr-2.0.2/lib/rsolr/client.rb:195:in `rescue in execute'
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/rsolr-2.0.2/lib/rsolr/client.rb:185:in `execute'
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/rsolr-2.0.2/lib/rsolr/client.rb:180:in `send_and_receive'
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/activesupport-5.0.3/lib/active_support/notifications.rb:164:in `block in instrument'
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/activesupport-5.0.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/activesupport-5.0.3/lib/active_support/notifications.rb:164:in `instrument'
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `get'
(pry):2:in `<main>'
/home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
from /home/web/.rvm/gems/ruby-2.3.3@canadadrugs/gems/rsolr-2.0.2/lib/rsolr/client.rb:195:in `rescue in execute'
```

### PR DESCRIPTION
**Pull request by JasonBarnabe**
Faraday supports `no_proxy` when you give it a URL when creating a connection. So let's do that.

Fixes #182.

### CODE REVIEW

File: lib/rsolr/client.rb [hunk 1]
```diff
@@ -33,6 +32,7 @@ def initialize connection, options = {}
     @update_format = options.delete(:update_format) || RSolr::JSON::Generator
     @update_path = options.fetch(:update_path, 'update')
     @options = options
+    @connection = connection
```
Comment (jcoyne) [inline lib/rsolr/client.rb]: Do we need this line?  Can we just make the connection lazily?

Comment (JasonBarnabe) [inline lib/rsolr/client.rb]: I think it is lazy already. I also misunderstood this line, which is why I moved it. This is setting `@connection` from the `connection` argument, not calling the `connection` method. I will move it back as this change should not be needed.
